# Generated by Django 2.1.5 on 2019-02-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
