# Generated by Django 2.1.2 on 2018-11-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email',)},
        ),
    ]
