# Generated by Django 2.1.5 on 2019-01-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_attachments_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
