# Generated by Django 2.1.2 on 2018-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
