# Generated by Django 2.1.2 on 2018-11-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20181115_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
