# Generated by Django 2.1.5 on 2019-02-12 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_to',
            field=models.ManyToManyField(related_name='document_shared_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
