# Generated by Django 2.2.4 on 2019-12-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20191231_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
