# Generated by Django 2.2.3 on 2019-08-08 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='scheduled_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='scheduled_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
