# Generated by Django 2.2.3 on 2019-08-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190808_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='sender',
            new_name='from_account',
        ),
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(default='admin@mp.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='rendered_message_body',
            field=models.TextField(null=True),
        ),
    ]
