# Generated by Django 2.2.4 on 2019-12-31 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_account_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
    ]
