# Generated by Django 2.1.2 on 2019-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_auto_20180410_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
