# Generated by Django 2.1.2 on 2019-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20181113_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='close_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
